variables:
  ANGULAR_CLI_VERSION: 11.0.0

stages:
  - install
  - build_and_test

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node-modules/
  policy: pull

webapp:install:
  stage: install
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  script:
    - npm ci --cache .npm --prefer-offline
  cache:
    <<: *global_cache
    policy: pull-push
  only:
    - master
    - develop
  tags:
    - docker


webapp:build:
  stage: build_and_test
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  needs:
    - job: webapp:install
      artifacts: true
  script:
    - npm ci --cache .npm --prefer-offline
    - ng build --prod
  artifacts:
    expire_in: 7 day
    paths:
      - dist/
  tags:
    - docker
  only:
    - master
    - develop
  cache:
    <<: *global_cache

webapp:test:karma:
  stage: build_and_test
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  needs:
    - job: webapp:install
      artifacts: true
  allow_failure: false
  script:
    - npm ci --cache .npm --prefer-offline
    - ng test --code-coverage --progress false --watch false
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - coverage/
    expire_in: 30 day
  tags:
    - docker
  only:
    - master
    - develop
  cache:
    <<: *global_cache
