variables:
  ANGULAR_CLI_VERSION: 11.0.0

stages:
  - install
  - build_and_test

webapp:install:
  stage: install
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  script:
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    #    key:
    #      files:
    #        - package-lock.json
    paths:
      - node_modules/
    policy: push
  only:
    - master
    - develop
  tags:
    - docker


webapp:build:
  stage: build_and_test
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  needs:
    - job: webapp:install
      artifacts: true
  script:
    - ng build --prod
  artifacts:
    expire_in: 7 day
    paths:
      - dist/
  tags:
    - docker
  only:
    - master
    - develop

webapp:test:karma:
  stage: build_and_test
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  needs:
    - job: webapp:install
      artifacts: true
  allow_failure: false
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - coverage/
    expire_in: 30 day
  tags:
    - docker
  only:
    - master
    - develop
