variables:
  ANGULAR_CLI_VERSION: 11.0.0

stages:
  - install
  - test
  - release
  - build
  - deploy

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
  policy: pull

install:
  stage: install
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  script:
    - npm i --cache .npm --prefer-offline
  cache:
    <<: *global_cache
    policy: push
  only:
    - master
    - develop
  tags:
    - docker

test:karma:
  stage: test
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  needs:
    - job: install
      artifacts: true
  allow_failure: false
  script:
    - npm i --cache .npm --prefer-offline
    - ng test --code-coverage --progress false --watch false
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days
  tags:
    - docker
  only:
    - master
    - develop
  cache:
    <<: *global_cache

release:
  stage: release
  image: node:13
  needs:
    - job: install
    - job: test:karma
  allow_failure: false
  before_script:
    - npm install @semantic-release/changelog @semantic-release/npm @semantic-release/git @semantic-release/gitlab
  script:
    - npx semantic-release
  tags:
    - docker
  only:
    - master

build:
  stage: build
  image: trion/ng-cli-karma:${ANGULAR_CLI_VERSION}
  needs:
    - job: install
      artifacts: true
    - job: release
  allow_failure: false
  script:
    - npm i --cache .npm --prefer-offline
    - ng build --prod
  artifacts:
    expire_in: 7 days
    paths:
      - dist/
  tags:
    - docker
  only:
    - master
  cache:
    <<: *global_cache

deploy:
  stage: deploy
  image: alpine
  needs:
    - job: install
      artifacts: true
    - job: build
      artifacts: true
    - job: release
  allow_failure: false
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 44' --progress --delete dist/ gitlab@lu-church.de:/var/www/podcastination-webapp/
  tags:
    - docker
  only:
    - master
  cache:
    <<: *global_cache
